In [1]:
import numpy as np

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [4]:
a = np.random.randint(1, 100,(3, 3))
a

array([[34,  3, 89],
       [68, 11, 48],
       [32, 72, 96]])

In [5]:
b = a.copy()
b

array([[34,  3, 89],
       [68, 11, 48],
       [32, 72, 96]])

In [8]:
c = a.copy()
c
b.sort()
b
c.sort(axis=0)
c
# sort : 정렬 인데 axis가 븥으면 어떤 일이 나타날까?

array([[34,  3, 89],
       [68, 11, 48],
       [32, 72, 96]])

array([[ 3, 34, 89],
       [11, 48, 68],
       [32, 72, 96]])

array([[32,  3, 48],
       [34, 11, 89],
       [68, 72, 96]])

In [9]:
d = a.copy()
d.sort(axis=1)
d
# sort에 (axis=1) 넣은것과 안넣은 것 똑같네?

array([[ 3, 34, 89],
       [11, 48, 68],
       [32, 72, 96]])

In [10]:
e = np.arange(25).reshape((5, 5))
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
e[0]

array([0, 1, 2, 3, 4])

In [13]:
e[0][0]

0

In [14]:
# fancy indexing
e[0,0]

0

In [16]:
# 슬라이싱
e[1:, 1:]
e[1:][1:]
# 검사하지 않는 숙제 - 둘 어떤 차이인지

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
e[1:-1, 1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [18]:
# 0과 1 행렬  e의 0번지와 1번지
e[np.array([0,1])]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
# (0, 0), (1, 1), (2, 2)에 해당하는 값을 보여주는 것  (행,열)
e[(0, 1, 2), (0, 1, 2)] # 행, 열 이어서 튜플로 패싱한다고 생각해도 ㅇ

array([ 0,  6, 12])

In [21]:
# e 의 나머지가 0인 값들
e[e%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [22]:
e[e<15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# boolean  [] 대괄호의 유무....
e < 15

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])